### ISSUE TITLE
Provide an openAll method

### ISSUE THREAD

**Issue by chocolateboy** [AcceDe-Web/accordion#1]
(Thanks for this and the [tabs implementation](https://github.com/AcceDe-Web/tablist)!)

It would be nice if there was an `openAll` method to complement `closeAll`.

### Related

- https://github.com/w3c/aria-practices/issues/304

**Comment by enwin** [comment]
Hey!

This has been too long, sorry for the late reply. Working on it today, this should be done by the end of the day. (In case that 5 month later you still need it.)

**Comment by enwin** [comment]
Aaaaand done!
Also pushed on npm (`v1.1.0`)

Cheers!
