### ISSUE TITLE
[Question] How to use for an "in-place toggle"?

### ISSUE THREAD

**Issue by Spone** [AcceDe-Web/accordion#3]
Hi there, thank you for this very promising library! We are using it in an upcoming project.

I have a specific use case and I'm wondering if this library is a good fit for it:

I have this button:

![image](https://user-images.githubusercontent.com/38524/57768013-f8db2300-770a-11e9-9769-374009baac0c.png)

that takes focus from keyboard:

![image](https://user-images.githubusercontent.com/38524/57771079-08119f00-7712-11e9-8a61-4935d715d806.png)

When I click it (or press Return/Space), I want to "replace" it visually with the following buttons:

![image](https://user-images.githubusercontent.com/38524/57771113-1e1f5f80-7712-11e9-895a-494855a15680.png)
(initially the focus is kept on the original button)

then when I press Tab the first item in the content gets the focus:

![image](https://user-images.githubusercontent.com/38524/57771222-62aafb00-7712-11e9-8716-8ee671dbc522.png)

I managed to implement this with:

```css
button[aria-expanded="true"] > * {
  visibility: hidden;
}
```

and absolute positioning to make the content visible on top of the button.

I only have one issue: in Firefox the behavior is not the same if I press Space or Return while focusing the button. Return works as expected, but Space displays the content for a millisecond then hides it. It's probably a browser bug because `accordion` handles Space and Return the same way.

Do you think it's a proper use of the `accordion` script? Do you see any potential accessibilty issue in this implementation?

**Comment by sdussaut** [comment]
Hi!
Sorry for the late answer.
I don't think that is a proper use for the accordion script. The usecase you are talking about is not _per se_ an accordion.

You can achieve the same behaviour quite easily using `aria-*` attributes:

- `aria-expanded` on the button
- `aria-hidden` on the layer

If the two of them are not direct sibling, you should consider using `aria-controls` on the button and an `id` on the layer to link them.

Hope this helps.
